// 托盘图标（32×32 单色 logo）。由 scripts/gen-tray-icon.mjs 生成后内嵌 —— 不走文件路径，
// 开发/打包/asar 场景行为一致。改图标：改脚本重新生成替换本常量。
export const TRAY_ICON_DATAURL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA7klEQVR4nGMQFBRkGEg8oJaPOmDUAZQ64D8QGyKx99DTAXZQS5Ed85+eDuhEs/A4vR2wBM3CUno7gGqYFMV7kOKaECY6QRJrOczg50B8kwB+LkhCoiTFclKDlyh9xBpUQ4YDaqjpAF8sPsOH90P1wPhvqemAKYKQbIgP2yI5oAJK/6WWA4jFMAeA2KlQNstAOQBmjv1AOaBcEEeCJNYBcWQ4IA6qdw6UfkaJAygpB0D4NC51xBjkg2RQHDRo8eE4JPU+hMwn1jfIjiAWE7ScFAeA8GMkw1+QESUUO+CBIPkJkioOoAkedcCoAwbcAQDXlEHz/bUD4AAAAABJRU5ErkJggg=='
