// 托盘图标（32×32 茶青圆点）。由 scripts/gen-tray-icon.mjs 生成后内嵌 —— 不走文件路径，
// 开发/打包/asar 场景行为一致。改图标：改脚本重新生成替换本常量。
export const TRAY_ICON_DATAURL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAzklEQVR4nM2XwRGEIAxFrYCO9rg9UANbAxXsxWrowao0zsCMg6AYEz6Hd3Fk8oAEwvT5/yYk0OBcAUN8CUf4iIvfjKaAJQKx3hDiv2IC+8yWhsA5Sxz7SsAzAud4rsAsEDwxPxWQmHnTStT2XDp44pQTJQFOwj1JzEsBqxg8Ya8EWur8LaEmYDoET5iSgGbyVZPxKOA6CriSgEbt1/BDCsC3AJ6E8DKEH0RDHMXwy2iI6xjekAzRkkmuBLspPeYErC3PSxTyMMmBPc1UgAtsA54HJoB24RAAAAAASUVORK5CYII='
